[package]
name = "arithmetic_lang"
version = "0.1.0"
authors = ["Sean Hellum <seanhellum45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lex"
path = "src/lex.rs"
test = true

[dependencies]
